//friend const bool operator < (const text &, const nr &);
friend const bool operator < (const std::string &, const nr &);
friend const bool operator < (const char [], const nr &);
//friend const bool operator < (const char *&, const nr &);
friend const bool operator < (const char &, const nr &);
//friend const bool operator < (const signed char &, const nr &);
//friend const bool operator < (const unsigned char &, const nr &);
//friend const bool operator < (const nr &, const nr &);
friend const bool operator < (const long double &, const nr &);
friend const bool operator < (const double &, const nr &);
friend const bool operator < (const float &, const nr &);
friend const bool operator < (const signed long long int &, const nr &);
friend const bool operator < (const unsigned long long int &, const nr &);
friend const bool operator < (const signed long int &, const nr &);
friend const bool operator < (const unsigned long int &, const nr &);
friend const bool operator < (const signed int &, const nr &);
friend const bool operator < (const unsigned int &, const nr &);
friend const bool operator < (const signed short int &, const nr &);
friend const bool operator < (const unsigned short int &, const nr &);
//friend const bool operator < (const bool &, const nr &);

