//var (void) = default;
var (void);
//var (const container &);
var (const var &);
//var (const noware::container::text &);
var (const std::string &);
var (const char []);
//var (const signed char []);
//var (const unsigned char []);
//var (const char *&);
//var (const signed char *&);
//var (const unsigned char *&);
var (const char &);
//var (const signed char &);
//var (const unsigned char &);
var (const nr &);
var (const long double &);
var (const double &);
var (const float &);
var (const unsigned long long int &);
var (const unsigned long int &);
var (const unsigned int &);
var (const unsigned short int &);
var (const signed long long int &);
var (const signed long int &);
var (const signed int &);
var (const signed short int &);

var (const bool &);
