//friend const nr operator - (const text &, const nr &);
friend const nr operator - (const std::string &, const nr &);
friend const nr operator - (const char [], const nr &);
//friend const nr operator - (const unsigned char [], const nr &);
//friend const nr operator - (const signed char [], const nr &);
friend const nr operator - (const char &, const nr &);
//friend const nr operator - (const signed char &, const nr &);
//friend const nr operator - (const unsigned char &, const nr &);
friend const nr operator - (const cln::cl_N &, const nr &);
friend const nr operator - (const cln::cl_RA &, const nr &);
friend const nr operator - (const cln::cl_I &, const nr &);
friend const nr operator - (const cln::cl_SF &, const nr &);
friend const nr operator - (const cln::cl_FF &, const nr &);
friend const nr operator - (const cln::cl_DF &, const nr &);
friend const nr operator - (const cln::cl_LF &, const nr &);
friend const nr operator - (const long double &, const nr &);
friend const nr operator - (const double &, const nr &);
friend const nr operator - (const float &, const nr &);
friend const nr operator - (const signed long long int &, const nr &);
friend const nr operator - (const unsigned long long int &, const nr &);
friend const nr operator - (const signed long int &, const nr &);
friend const nr operator - (const unsigned long int &, const nr &);
friend const nr operator - (const signed int &, const nr &);
friend const nr operator - (const unsigned int &, const nr &);
friend const nr operator - (const signed short int &, const nr &);
friend const nr operator - (const unsigned short int &, const nr &);

