//friend const bool operator < (const text &, const number &);
friend const bool operator < (const std::string &, const number &);
friend const bool operator < (const char [], const number &);
//friend const bool operator < (const char *&, const number &);
friend const bool operator < (const char &, const number &);
//friend const bool operator < (const signed char &, const number &);
//friend const bool operator < (const unsigned char &, const number &);
//friend const bool operator < (const number &, const number &);
friend const bool operator < (const long double &, const number &);
friend const bool operator < (const double &, const number &);
friend const bool operator < (const float &, const number &);
friend const bool operator < (const signed long long int &, const number &);
friend const bool operator < (const unsigned long long int &, const number &);
friend const bool operator < (const signed long int &, const number &);
friend const bool operator < (const unsigned long int &, const number &);
friend const bool operator < (const signed int &, const number &);
friend const bool operator < (const unsigned int &, const number &);
friend const bool operator < (const signed short int &, const number &);
friend const bool operator < (const unsigned short int &, const number &);
//friend const bool operator < (const bool &, const number &);

