//const bool operator + (void) const;
const nr operator + (const nr &) const;
//const nr operator + (const text &) const;
const nr operator + (const std::string &) const;
const nr operator + (const char []) const;
//const nr operator + (const signed char []) const;
//const nr operator + (const unsigned char []) const;
//const nr operator + (const char *&) const;
const nr operator + (const char &) const;
//const nr operator + (const signed char &) const;
//const nr operator + (const unsigned char &) const;
//const nr operator + (const math::nr &) const;
const nr operator + (const cln::cl_N &) const;
//const nr operator + (const cln::cl_R &) const;
const nr operator + (const cln::cl_RA &) const;
const nr operator + (const cln::cl_I &) const;
const nr operator + (const cln::cl_SF &) const;
const nr operator + (const cln::cl_FF &) const;
const nr operator + (const cln::cl_DF &) const;
const nr operator + (const long double &) const;
const nr operator + (const double &) const;
const nr operator + (const float &) const;
const nr operator + (const signed long long int &) const;
const nr operator + (const unsigned long long int &) const;
const nr operator + (const signed long int &) const;
const nr operator + (const unsigned long int &) const;
const nr operator + (const signed int &) const;
const nr operator + (const unsigned int &) const;
const nr operator + (const signed short int &) const;
const nr operator + (const unsigned short int &) const;

