any (void) = default;
//any (const container &);
any (const any &);
//any (const noware::container::text &);
any (const std::string &);
any (const char []);
//any (const signed char []);
//any (const unsigned char []);
//any (const char *&);
//any (const signed char *&);
//any (const unsigned char *&);
any (const char &);
any (const signed char &);
any (const unsigned char &);
any (const number &);
any (const long double &);
any (const double &);
any (const float &);
any (const signed long long int &);
any (const unsigned long long int &);
any (const signed long int &);
any (const unsigned long int &);
any (const signed int &);
any (const unsigned int &);
any (const signed short int &);
any (const unsigned short int &);
any (const bool &);

